name: build-push-SafePKT-container-image

on:
  push:
    branches:
      - library-verification

jobs:

  build-push-base-safepkt-container-image:

    name: Build and push SafePKT container image

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push safepkt/verifier
        uses: docker/build-push-action@v2.2.2
        with:
          context: provisioning/web-server/safepkt
          push: true
          build-args: |
            UID_GID=1000:1000
            RVT_DIR=/home/rust-verification-tools
            LLVM_VERSION=10
          cache-from: type=registry,ref=safepkt/verifier:latest
          cache-to: type=inline
          tags: |
            safepkt/verifier:latest
